using Microsoft.ML.Data;

namespace InsiderThreatDetection.Core.Models
{
    /// <summary>
    /// Represents the prediction output generated by the trained
    /// Insider Threat Detection machine learning model.
    /// 
    /// This class is used by ML.NET to map model output columns
    /// to strongly typed properties.
    /// </summary>
    public class ThreatPrediction
    {
        /// <summary>
        /// The final binary classification result produced by the model.
        /// 
        /// True  = Malicious Insider Behaviour
        /// False = Normal Behaviour
        /// 
        /// This property is automatically mapped from the model's
        /// "PredictedLabel" output column.
        /// </summary>
        [ColumnName("PredictedLabel")]
        public bool PredictedLabel { get; set; }

        /// <summary>
        /// The model's estimated probability that the behaviour
        /// belongs to the positive class (Malicious).
        /// 
        /// Value range: 0.0 – 1.0
        /// </summary>
        public float Probability { get; set; }

        /// <summary>
        /// Raw model score before probability calibration.
        /// 
        /// Positive values indicate higher likelihood of malicious behaviour.
        /// Negative values indicate normal behaviour.
        /// 
        /// This is primarily useful for analysis and debugging.
        /// </summary>
        public float Score { get; set; }
    }
}